SET FOREIGN_KEY_CHECKS = 0;

DROP TRIGGER IF EXISTS trg_dn_ai;
DROP TRIGGER IF EXISTS trg_dn_au;
DROP TRIGGER IF EXISTS trg_dn_ad;

DROP TRIGGER IF EXISTS trg_do_ai;
DROP TRIGGER IF EXISTS trg_do_au;
DROP TRIGGER IF EXISTS trg_do_ad;

SET FOREIGN_KEY_CHECKS = 1;
DELIMITER $$